# Master playbook

- hosts:        localhost
  roles:
    - { role: mythtv-deb, when:  ansible_pkg_mgr == "apt" }
    - { role: mythtv-rpm, when:  ansible_pkg_mgr == "yum" }
    - role: qt4
    - role: buildslave
