# roles/mythtv-rpm/tasks/lame-build.yml

- shell:            /bin/rpm -q --quiet lame-devel && echo installed || echo missing
  register:         lame

- shell:            /bin/test -f {{ lame_rpm }} && echo built || echo missing
  register:         build_lame

- name: install LAME build requirements
  yum:  name={{ item }} state=installed
  when: lame.stdout == "missing" and build_lame.stdout == "missing"
  with_items:
    - rpm-build
    - ncurses-devel
    - gtk+-devel

- name: build LAME 
  command: rpmbuild --rebuild {{ lame_src }}
  when: lame.stdout == "missing" and build_lame.stdout == "missing"

- name: install LAME after local build
  command: yum -y localinstall {{ lame_rpms_all }}
  when: lame.stdout == "missing"
