# roles/mythtv-rpm/tasks/setup-rpmfusion.yml

- shell:            /bin/rpm -q --quiet rpmfusion-free-release && echo installed || echo missing
  register:         rpmfusion

- name: setup RPMfusion repository
  command: yum localinstall -y --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm 
  when: ansible_distribution == "Fedora" and rpmfusion.stdout == "missing"
