# roles/mythtv-deb/tasks/main.yml

- name: install compilers and build essentials
  apt:  name={{ item }} state=installed
  with_items:
    - git 
    - g++ 
    - make 
    - build-essential 
    - yasm
    - automake
    - libtool
    - ccache
    - pkg-config 

- name: install compilers and build essentials 2 (debian)
  apt:  name={{ item }} state=installed
  when: ansible_lsb.codename == "jessie"
  with_items:
    - libtool-bin

- name: install compilers and build essentials 2 (ubuntu)
  apt:  name={{ item }} state=installed
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int >= 15
  with_items:
    - libtool-bin

- name: install mythtv essential build libraries
  apt:  name={{ item }} state=installed
  with_items:
    - uuid-dev 
    - libfreetype6-dev 
    - libmp3lame-dev
    - libxv-dev
    - libxxf86vm-dev 
    - libxinerama-dev
    - libxrandr-dev
    - libxml2-dev
    - libavahi-compat-libdnssd-dev
    - libexiv2-dev
    - libasound2-dev
    - libegl1-mesa-dev
# Added OpenGL ES
#    - libgles2-mesa-dev

- name: install mythtv extra build libraries
  apt:  name={{ item }} state=installed
  with_items:
    - libva-dev
    - libvdpau-dev

- name: install mythtv essential python modules
  apt:  name={{ item }} state=installed
  with_items:
    - python-mysqldb 
    - python-lxml 
    - python-urlgrabber
    - python-oauth

- name: install mythtv essential perl modules
  apt:  name={{ item }} state=installed
  with_items:
    - libdbi-perl 
    - libdbd-mysql-perl
    - libnet-upnp-perl
    - libwww-perl 
    - libio-socket-inet6-perl
    - libdate-manip-perl
    - libxml-simple-perl
    - libxml-xpath-perl 
    - libimage-size-perl 
    - libdatetime-format-iso8601-perl 
    - libsoap-lite-perl 
    - libjson-perl

- name: install mythtv essential plugin libraries
  apt:  name={{ item }} state=installed
  with_items:
    - libvorbis-dev 
    - libflac-dev 
    - libflac++-dev 
    - libtag1-dev
    - libcdio-dev 
    - libcdio-paranoia-dev
    - libmysqlclient-dev
