# roles/mythtv-deb/tasks/qt5.yml
- name: enable wheezy backports repo
  apt_repository: repo='deb http://ftp2.de.debian.org/debian wheezy-backports main contrib non-free' state=present

- name: install qt5
  apt:  name={{ item }} state=installed
  with_items:
    - libqt5core5a
    - libqt5webkit5-dev
    - libqt5opengl5-dev
    - libqt5script5
    - qtscript5-dev
    - qt5-default
    - qt5-qmake

- name: install mythtv essential runtime libraries
  apt:  name={{ item }} state=installed
  with_items:
    - libqt5sql5-mysql
